// Netflix Price Index data for regional pricing
// Source: tompec/netflix-prices, CC-BY-4.0, https://github.com/tompec/netflix-prices
// Source snapshot: https://raw.githubusercontent.com/tompec/netflix-prices/main/data/latest.json
// Source commit: a46477c39bc95049bca452b4476d0ed1ac64d1ea
// Generated by: scripts/generate-netflix-index.mjs

export interface NetflixPriceIndexEntry {
  multiplier: number;
  standardPriceUsd: number;
  source: 'tompec-netflix-prices' | 'inferred';
  inferredFrom?: string;
}

// Netflix Standard ad-free subscription multipliers relative to US (US = 1.0).
// Multiplier = country standard price in USD / US standard price in USD.
export const NETFLIX_PRICE_INDEX: Record<string, NetflixPriceIndexEntry> = {
  AD: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  AE: {
    multiplier: 0.6673,
    standardPriceUsd: 13.34,
    source: 'tompec-netflix-prices',
  },
  AF: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  AG: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  AI: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  AL: {
    multiplier: 0.4662,
    standardPriceUsd: 9.32,
    source: 'tompec-netflix-prices',
  },
  AM: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  AO: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  AQ: {
    multiplier: 0.8999,
    standardPriceUsd: 17.99,
    source: 'tompec-netflix-prices',
  },
  AR: {
    multiplier: 0.5408,
    standardPriceUsd: 10.81,
    source: 'tompec-netflix-prices',
  },
  AS: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  AT: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  AU: {
    multiplier: 0.7394,
    standardPriceUsd: 14.78,
    source: 'tompec-netflix-prices',
  },
  AW: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  AX: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  AZ: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  BA: {
    multiplier: 0.4662,
    standardPriceUsd: 9.32,
    source: 'tompec-netflix-prices',
  },
  BB: {
    multiplier: 0.7649,
    standardPriceUsd: 15.29,
    source: 'tompec-netflix-prices',
  },
  BD: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BE: {
    multiplier: 0.991,
    standardPriceUsd: 19.81,
    source: 'tompec-netflix-prices',
  },
  BF: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BG: {
    multiplier: 0.5243,
    standardPriceUsd: 10.48,
    source: 'tompec-netflix-prices',
  },
  BH: {
    multiplier: 0.5248,
    standardPriceUsd: 10.49,
    source: 'tompec-netflix-prices',
  },
  BI: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BJ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BL: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  BM: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  BN: {
    multiplier: 0.6998,
    standardPriceUsd: 13.99,
    source: 'tompec-netflix-prices',
  },
  BO: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  BQ: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  BR: {
    multiplier: 0.4402,
    standardPriceUsd: 8.8,
    source: 'tompec-netflix-prices',
  },
  BS: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  BT: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BV: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  BW: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  BY: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  BZ: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  CA: {
    multiplier: 0.6858,
    standardPriceUsd: 13.71,
    source: 'tompec-netflix-prices',
  },
  CC: {
    multiplier: 0.6688,
    standardPriceUsd: 13.37,
    source: 'tompec-netflix-prices',
  },
  CD: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CF: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CG: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CH: {
    multiplier: 1.4472,
    standardPriceUsd: 28.93,
    source: 'tompec-netflix-prices',
  },
  CI: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CK: {
    multiplier: 0.7574,
    standardPriceUsd: 15.14,
    source: 'tompec-netflix-prices',
  },
  CL: {
    multiplier: 0.5563,
    standardPriceUsd: 11.12,
    source: 'tompec-netflix-prices',
  },
  CM: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CN: {
    multiplier: 0.6258,
    standardPriceUsd: 12.51,
    source: 'inferred',
    inferredFrom: 'HK',
  },
  CO: {
    multiplier: 0.4107,
    standardPriceUsd: 8.21,
    source: 'tompec-netflix-prices',
  },
  CR: {
    multiplier: 0.7499,
    standardPriceUsd: 14.99,
    source: 'tompec-netflix-prices',
  },
  CU: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  CV: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CW: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  CX: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  CY: {
    multiplier: 0.7284,
    standardPriceUsd: 14.56,
    source: 'tompec-netflix-prices',
  },
  CZ: {
    multiplier: 0.8109,
    standardPriceUsd: 16.21,
    source: 'tompec-netflix-prices',
  },
  DE: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  DJ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  DK: {
    multiplier: 1.007,
    standardPriceUsd: 20.13,
    source: 'tompec-netflix-prices',
  },
  DM: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  DO: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  DZ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  EC: {
    multiplier: 0.4497,
    standardPriceUsd: 8.99,
    source: 'tompec-netflix-prices',
  },
  EE: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  EG: {
    multiplier: 0.1596,
    standardPriceUsd: 3.19,
    source: 'tompec-netflix-prices',
  },
  EH: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  ER: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  ES: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  ET: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  FI: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  FJ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  FK: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  FM: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  FO: {
    multiplier: 1.007,
    standardPriceUsd: 20.13,
    source: 'tompec-netflix-prices',
  },
  FR: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  GA: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GB: {
    multiplier: 0.8704,
    standardPriceUsd: 17.4,
    source: 'tompec-netflix-prices',
  },
  GD: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  GE: {
    multiplier: 0.6878,
    standardPriceUsd: 13.75,
    source: 'tompec-netflix-prices',
  },
  GF: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  GG: {
    multiplier: 0.8704,
    standardPriceUsd: 17.4,
    source: 'tompec-netflix-prices',
  },
  GH: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GI: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  GL: {
    multiplier: 1.007,
    standardPriceUsd: 20.13,
    source: 'tompec-netflix-prices',
  },
  GM: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GN: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GP: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  GQ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GR: {
    multiplier: 0.7284,
    standardPriceUsd: 14.56,
    source: 'tompec-netflix-prices',
  },
  GS: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  GT: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  GU: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  GW: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  GY: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  HK: {
    multiplier: 0.6258,
    standardPriceUsd: 12.51,
    source: 'tompec-netflix-prices',
  },
  HM: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  HN: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  HR: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  HT: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  HU: {
    multiplier: 0.6953,
    standardPriceUsd: 13.9,
    source: 'tompec-netflix-prices',
  },
  ID: {
    multiplier: 0.3532,
    standardPriceUsd: 7.06,
    source: 'tompec-netflix-prices',
  },
  IE: {
    multiplier: 0.991,
    standardPriceUsd: 19.81,
    source: 'tompec-netflix-prices',
  },
  IL: {
    multiplier: 0.8879,
    standardPriceUsd: 17.75,
    source: 'tompec-netflix-prices',
  },
  IM: {
    multiplier: 0.8704,
    standardPriceUsd: 17.4,
    source: 'tompec-netflix-prices',
  },
  IN: {
    multiplier: 0.2706,
    standardPriceUsd: 5.41,
    source: 'tompec-netflix-prices',
  },
  IO: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  IQ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  IR: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  IS: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  IT: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  JE: {
    multiplier: 0.8704,
    standardPriceUsd: 17.4,
    source: 'tompec-netflix-prices',
  },
  JM: {
    multiplier: 0.3497,
    standardPriceUsd: 6.99,
    source: 'tompec-netflix-prices',
  },
  JO: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  JP: {
    multiplier: 0.5013,
    standardPriceUsd: 10.02,
    source: 'tompec-netflix-prices',
  },
  KE: {
    multiplier: 0.2706,
    standardPriceUsd: 5.41,
    source: 'tompec-netflix-prices',
  },
  KG: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  KH: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  KI: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  KM: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  KN: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  KR: {
    multiplier: 0.4562,
    standardPriceUsd: 9.12,
    source: 'tompec-netflix-prices',
  },
  KW: {
    multiplier: 0.5998,
    standardPriceUsd: 11.99,
    source: 'tompec-netflix-prices',
  },
  KY: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  KZ: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  LA: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  LB: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  LC: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  LI: {
    multiplier: 1.4472,
    standardPriceUsd: 28.93,
    source: 'tompec-netflix-prices',
  },
  LK: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  LR: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  LS: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  LT: {
    multiplier: 0.6408,
    standardPriceUsd: 12.81,
    source: 'tompec-netflix-prices',
  },
  LU: {
    multiplier: 0.991,
    standardPriceUsd: 19.81,
    source: 'tompec-netflix-prices',
  },
  LV: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  LY: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MA: {
    multiplier: 0.3492,
    standardPriceUsd: 6.98,
    source: 'tompec-netflix-prices',
  },
  MC: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  MD: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  ME: {
    multiplier: 0.4662,
    standardPriceUsd: 9.32,
    source: 'tompec-netflix-prices',
  },
  MF: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  MG: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MH: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  MK: {
    multiplier: 0.4662,
    standardPriceUsd: 9.32,
    source: 'tompec-netflix-prices',
  },
  ML: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MM: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MN: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MO: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  MP: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  MQ: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  MR: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MS: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  MT: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  MU: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MV: {
    multiplier: 0.6998,
    standardPriceUsd: 13.99,
    source: 'tompec-netflix-prices',
  },
  MW: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  MX: {
    multiplier: 0.7714,
    standardPriceUsd: 15.42,
    source: 'tompec-netflix-prices',
  },
  MY: {
    multiplier: 0.6273,
    standardPriceUsd: 12.54,
    source: 'tompec-netflix-prices',
  },
  MZ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  NA: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  NC: {
    multiplier: 0.6998,
    standardPriceUsd: 13.99,
    source: 'tompec-netflix-prices',
  },
  NE: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  NF: {
    multiplier: 0.6688,
    standardPriceUsd: 13.37,
    source: 'tompec-netflix-prices',
  },
  NG: {
    multiplier: 0.2361,
    standardPriceUsd: 4.72,
    source: 'tompec-netflix-prices',
  },
  NI: {
    multiplier: 0.3497,
    standardPriceUsd: 6.99,
    source: 'tompec-netflix-prices',
  },
  NL: {
    multiplier: 0.9325,
    standardPriceUsd: 18.64,
    source: 'tompec-netflix-prices',
  },
  NO: {
    multiplier: 0.6738,
    standardPriceUsd: 13.47,
    source: 'tompec-netflix-prices',
  },
  NP: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  NR: {
    multiplier: 0.6998,
    standardPriceUsd: 13.99,
    source: 'tompec-netflix-prices',
  },
  NU: {
    multiplier: 0.7574,
    standardPriceUsd: 15.14,
    source: 'tompec-netflix-prices',
  },
  NZ: {
    multiplier: 0.7574,
    standardPriceUsd: 15.14,
    source: 'tompec-netflix-prices',
  },
  OM: {
    multiplier: 0.5248,
    standardPriceUsd: 10.49,
    source: 'tompec-netflix-prices',
  },
  PA: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  PE: {
    multiplier: 0.6043,
    standardPriceUsd: 12.08,
    source: 'tompec-netflix-prices',
  },
  PF: {
    multiplier: 0.6998,
    standardPriceUsd: 13.99,
    source: 'tompec-netflix-prices',
  },
  PG: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  PH: {
    multiplier: 0.3777,
    standardPriceUsd: 7.55,
    source: 'tompec-netflix-prices',
  },
  PK: {
    multiplier: 0.1436,
    standardPriceUsd: 2.87,
    source: 'tompec-netflix-prices',
  },
  PL: {
    multiplier: 0.6718,
    standardPriceUsd: 13.43,
    source: 'tompec-netflix-prices',
  },
  PM: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  PN: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  PR: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  PS: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  PT: {
    multiplier: 0.7574,
    standardPriceUsd: 15.14,
    source: 'tompec-netflix-prices',
  },
  PW: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  PY: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  QA: {
    multiplier: 0.5998,
    standardPriceUsd: 11.99,
    source: 'tompec-netflix-prices',
  },
  RE: {
    multiplier: 0.7869,
    standardPriceUsd: 15.73,
    source: 'tompec-netflix-prices',
  },
  RO: {
    multiplier: 0.6408,
    standardPriceUsd: 12.81,
    source: 'tompec-netflix-prices',
  },
  RS: {
    multiplier: 0.5243,
    standardPriceUsd: 10.48,
    source: 'tompec-netflix-prices',
  },
  RU: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'inferred',
    inferredFrom: 'BY',
  },
  RW: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SA: {
    multiplier: 0.6533,
    standardPriceUsd: 13.06,
    source: 'tompec-netflix-prices',
  },
  SB: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SC: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SD: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SE: {
    multiplier: 0.7994,
    standardPriceUsd: 15.98,
    source: 'tompec-netflix-prices',
  },
  SG: {
    multiplier: 0.902,
    standardPriceUsd: 18.03,
    source: 'tompec-netflix-prices',
  },
  SH: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SI: {
    multiplier: 0.5243,
    standardPriceUsd: 10.48,
    source: 'tompec-netflix-prices',
  },
  SJ: {
    multiplier: 0.6738,
    standardPriceUsd: 13.47,
    source: 'tompec-netflix-prices',
  },
  SK: {
    multiplier: 0.6703,
    standardPriceUsd: 13.4,
    source: 'tompec-netflix-prices',
  },
  SL: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SM: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  SN: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SO: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SR: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  SS: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  ST: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  SV: {
    multiplier: 0.4997,
    standardPriceUsd: 9.99,
    source: 'tompec-netflix-prices',
  },
  SX: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  SZ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TC: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  TD: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TF: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  TG: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TH: {
    multiplier: 0.5443,
    standardPriceUsd: 10.88,
    source: 'tompec-netflix-prices',
  },
  TJ: {
    multiplier: 0.6878,
    standardPriceUsd: 13.75,
    source: 'tompec-netflix-prices',
  },
  TK: {
    multiplier: 0.7574,
    standardPriceUsd: 15.14,
    source: 'tompec-netflix-prices',
  },
  TL: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TM: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  TN: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TO: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TR: {
    multiplier: 0.3262,
    standardPriceUsd: 6.52,
    source: 'tompec-netflix-prices',
  },
  TT: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  TV: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  TW: {
    multiplier: 0.5983,
    standardPriceUsd: 11.96,
    source: 'tompec-netflix-prices',
  },
  TZ: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  UA: {
    multiplier: 0.4367,
    standardPriceUsd: 8.73,
    source: 'tompec-netflix-prices',
  },
  UG: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  UM: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  US: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  UY: {
    multiplier: 0.8499,
    standardPriceUsd: 16.99,
    source: 'tompec-netflix-prices',
  },
  UZ: {
    multiplier: 0.5828,
    standardPriceUsd: 11.65,
    source: 'tompec-netflix-prices',
  },
  VA: {
    multiplier: 0.8159,
    standardPriceUsd: 16.31,
    source: 'tompec-netflix-prices',
  },
  VC: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  VE: {
    multiplier: 0.2996,
    standardPriceUsd: 5.99,
    source: 'tompec-netflix-prices',
  },
  VG: {
    multiplier: 0.7749,
    standardPriceUsd: 15.49,
    source: 'tompec-netflix-prices',
  },
  VI: {
    multiplier: 1.0,
    standardPriceUsd: 19.99,
    source: 'tompec-netflix-prices',
  },
  VN: {
    multiplier: 0.4392,
    standardPriceUsd: 8.78,
    source: 'tompec-netflix-prices',
  },
  VU: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  WF: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  WS: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  XK: {
    multiplier: 0.4662,
    standardPriceUsd: 9.32,
    source: 'inferred',
    inferredFrom: 'AL',
  },
  YE: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  YT: {
    multiplier: 0.8744,
    standardPriceUsd: 17.48,
    source: 'tompec-netflix-prices',
  },
  ZA: {
    multiplier: 0.5453,
    standardPriceUsd: 10.9,
    source: 'tompec-netflix-prices',
  },
  ZM: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
  ZW: {
    multiplier: 0.3997,
    standardPriceUsd: 7.99,
    source: 'tompec-netflix-prices',
  },
};

export const DEFAULT_NETFLIX_MULTIPLIER = 0.70;

export function getNetflixMultiplier(regionCode: string): number {
  return NETFLIX_PRICE_INDEX[regionCode]?.multiplier ?? DEFAULT_NETFLIX_MULTIPLIER;
}

export function getAllNetflixData(): Record<
  string,
  {
    multiplier: number;
    source: 'tompec-netflix-prices' | 'inferred' | 'default';
    inferredFrom?: string;
  }
> {
  const result: Record<
    string,
    {
      multiplier: number;
      source: 'tompec-netflix-prices' | 'inferred' | 'default';
      inferredFrom?: string;
    }
  > = {};

  for (const [regionCode, entry] of Object.entries(NETFLIX_PRICE_INDEX)) {
    result[regionCode] = {
      multiplier: entry.multiplier,
      source: entry.source,
      ...(entry.inferredFrom ? { inferredFrom: entry.inferredFrom } : {}),
    };
  }

  return result;
}
